version: '3.8'
services:
  db:
    image: postgres
    environment:
      {
        POSTGRES_PASSWORD=11,
        POSTGRES_DB=postgres
      }
    ports:
      - "5432"
  app:
    image: demo2
    ports:
      - "8081:8081"
    build: ./
    depends_on:
      - db